assets/src/modules/sm/App/providers/globalKbdShortcutsFactory.js, assets/src/modules/sm/Search/controllers/SearchController.js
(Requested on this issue: https://github.com/ComputerScienceHouse/schedulemaker/issues/82 )
=> Changed ctrl+enter keybind to enter on the search form elements.

assets/src/modules/sm/App/controllers/AppController.js, assets/src/modules/sm/Schedule/directives/scheduleDirective.js, assets/src/modules/sm/Schedule/directives/svgTextLineDirective.js, package.json, readme.md
* Removed extra debugging log call
* Fixed scaling of text in schedule display
* Improved readme
* Fixed https://github.com/ComputerScienceHouse/schedulemaker/issues/95 (the & bug)
=> A bunch of bug fixes and improvements (see description)

api/entity.php, api/generate.php, api/schedule.php, api/search.php, api/status.php, inc/databaseConn.php, tools/processDump.php, tools/pruneSchedules.php
Note: This still needs testing
=> Deprecate all mysql_ commands.

api/entity.php, inc/databaseConn.php
There were two variables that weren't right.
=> Fixes two broken db references.

tools/processDump.php
There are still a few parsing errors, but this should help schedule maker get back up and running.
Fixes #134
=> Fix Major Parse Errors

assets/src/modules/sm/App/styles/bootstrap.css, index.php, package.json, readme.md
Fixed the insecure font issue as well as updating the README and updated a few older assets.
Fixes #149
=> Fixed Insecure Font Issue, Updated README, and Updated Vendored Assets

tools/Parser.php, tools/processDump.php
The parser keeps stalling when in the cronjob. Because of that I want to fully understand it and be able to fix it when things break. The first step was splitting all the functions into a new Class to take advantage of OO PHP.
The script still runs identically to before, except now it's a little more manageable, and it can be a little more easily understood in this format.
=> Splitting up Parser and using more PHP7 and OOP

tools/Parser.php, tools/processDump.php
Updating the parsing script to production
=> Updating Parsing Script

assets/src/modules/sm/App/styles/global.css, package.json
Now it doesn't show the x and the spinner at the same time when loading data
=> Fixing Loading Style

api/generate.php, api/src/Generate.php
Wait to merge after #159 
Fixing and refactoring api routes
=> Refactoring and Fixing Style of Routes in API

index.php
At the suggestion of @bgrawi, I added my name to the footer as the current developer
Also increased the size of the CSH logo to fit the footer slightly better
=> Adding name to footer

tools/Parser.php
Class numbers were failing due to this type definition
Fixes #180
=> Updating parser to take string course numbers

Dockerfile
Ran Dockerfile through a linter, and reverted to fix broken OKD builds
=> Slight cleanup and revert to 7.1

.travis.yml
Updating PHP versions in Travis
=> Updating travis versions

api/entity.php, api/generate.php, api/rmp.php, api/schedule.php, api/search.php, api/src/Generate.php, api/src/S3Manager.php, api/status.php, inc/ajaxError.php, inc/databaseConn.php, inc/stringFunctions.php, inc/timeFunctions.php
This one is big. It touches basically every file.
This is part of a larger effort to conform the files to PSR-2
=> Cleaning File Style

assets/src/modules/sm/Schedule/directives/scheduleActionsDirective.js, package.json
=> account for current page and page size when hiding schedules (fix #183)

README.md, assets/src/modules/sm/Generate/controllers/GenerateController.js, assets/src/modules/sm/Generate/controllers/GenerateScheduleCoursesController.js, assets/src/modules/sm/Schedule/directives/scheduleActionsDirective.js, assets/src/modules/sm/Search/controllers/SearchController.js, assets/src/modules/sm/app.js, inc/config.env.php, index.php
I added the events into generate schedule and the find function to log data of what people searched. SDK's exist so I didn't think error management was the best use of a few events.
=> DataDog RUM + Events

.github/dependabot.yml
Let GitHub automatically create PRs updating deps
=> Set up auto updates for deps

inc/timeFunctions.php
Changing non-schedule items to go in 15 minute intervals to account for weird class start and end times due to corona.
=> Update timeFunctions.php to go in 15 min intervals for non-schedule items

Dockerfile, index.php, package.json
=> index: use https where possible

Dockerfile, index.php, package.json
Seems to work on dev instance, closes #286
=> Bring up master to develop

.github/dependabot.yml
Only ping for minor/major, no patch
=> Have dependabot be less annoying

tools/processDump.php
=> Fix School Listing Import
